#!/bin/bash
# connections – manage OpenSSH, Squid, Dropbear, OpenVPN, SOCKS, SSL tunnel, SSLH (menu option [03] CONNECTION MODE).

# Load color helpers (install path vs dev path)
if [[ -f /etc/SSHPlus/colors ]]; then
	source /etc/SSHPlus/colors
elif [[ -f /bin/colors ]]; then
	source /bin/colors
elif [[ -f "$(dirname "$0")/colors" ]]; then
	source "$(dirname "$0")/colors"
fi
[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
	ram1=$(free -h | grep -i mem | awk {'print $2'})
	ram2=$(free -h | grep -i mem | awk {'print $4'})
	ram3=$(free -h | grep -i mem | awk {'print $3'})
	uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
	system=$(cat /etc/issue.net)
	fun_bar() {
		command[0]="$1"
		command[1]="$2"
		(
			[[ -e $HOME/fim ]] && rm $HOME/fim
			[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
			${command[0]} >/dev/null 2>&1
			${command[1]} >/dev/null 2>&1
			touch $HOME/fim
		) >/dev/null 2>&1 &
		tput civis
		# Use color functions for progress bar
		yellow_code=$(get_color_code "yellow")
		red_code=$(get_color_code "red")
		white_code=$(get_color_code "white")
		green_code=$(get_color_code "green")
		reset_code=$(get_reset_code)
		echo -ne "${yellow_code}WAIT ${white_code}- ${yellow_code}["
		while true; do
			for ((i = 0; i < 18; i++)); do
				echo -ne "${red_code}#"
				sleep 0.1s
			done
			[[ -e $HOME/fim ]] && rm $HOME/fim && break
			echo -e "${yellow_code}]"
			sleep 1s
			tput cuu1
			tput dl1
			echo -ne "${yellow_code}WAIT ${white_code}- ${yellow_code}["
		done
		echo -e "${yellow_code}]${white_code} -${green_code} OK !${white_code}${reset_code}"
		tput cnorm
	}

	verif_ptrs() {
		porta=$1
		PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
		for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
			svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
			[[ "$porta" = "$pton" ]] && {
				echo ""
				color_echo_n "PORT " "red"
				color_echo_n "$porta " "yellow"
				color_echo_n "IN USE BY " "red"
				color_echo "$svcs" "white"
				sleep 3
				fun_connections
			}
		done
	}

	inst_sqd() {
		if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
			banner_info_red "            REMOVE SQUID PROXY              "
			echo ""
			color_echo_n "DO YOU REALLY WANT TO REMOVE SQUID " "green"
			color_echo_n "? " "red"
			color_echo_n "[y/n]: " "yellow"
			read resp
			[[ "$resp" = 'y' ]] && {
				echo ""
				color_echo "REMOVING THE SQUID PROXY !" "green"
				echo ""
				rem_sqd() {
					[[ -d "/etc/squid" ]] && {
						apt-get remove squid -y >/dev/null 2>&1
						apt-get purge squid -y >/dev/null 2>&1
						rm -rf /etc/squid >/dev/null 2>&1
					}
					[[ -d "/etc/squid3" ]] && {
						apt-get remove squid3 -y >/dev/null 2>&1
						apt-get purge squid3 -y >/dev/null 2>&1
						rm -rf /etc/squid3 >/dev/null 2>&1
					}
				}
				fun_bar 'rem_sqd'
				echo ""
				msg_ok "SQUID REMOVED SUCCESSFULLY !"
				sleep 2
				clear
				fun_connections
			} || {
				echo ""
				msg_err "Returning..."
				sleep 2
				clear
				fun_connections
			}
		else
			clear
			banner_info "              SQUID INSTALLER                "
			echo ""
			IP=$(wget -qO- ipv4.icanhazip.com)
			echo -ne "\033[1;32mTO CONTINUE CONFIRM YOUR IP: \033[1;37m"
			read -e -i $IP ipdovps
			[[ -z "$ipdovps" ]] && {
				echo ""
				msg_err "Invalid IP"
				echo ""
				read -p "Enter your IP: " IP
			}
			echo ""
			color_echo_n "WHICH PORTS DO YOU WANT TO USE IN THE SQUID " "yellow"
			color_echo "?" "red"
			echo ""
			msg_warn "[!] SET THE PORTS IN SEQUENCE EX: 80 8080 8799"
			echo ""
			color_echo_n "INFORM THE PORTS: " "green"
			read portass
			[[ -z "$portass" ]] && {
				echo ""
				msg_err "Invalid port!"
				sleep 3
				fun_connections
			}
			for porta in $(echo -e $portass); do
				verif_ptrs $porta
			done
			echo ""
			color_echo "INSTALLING SQUID PROXY" "green"
			echo ""
			fun_bar 'apt-get update -y' 'instsqd'
			if [[ -d "/etc/squid/" ]]; then
				var_sqd="/etc/squid/squid.conf"
				var_pay="/etc/squid/payload.txt"
			elif [[ -d "/etc/squid3/" ]]; then
				var_sqd="/etc/squid3/squid.conf"
				var_pay="/etc/squid3/payload.txt"
			else
				echo ""
				msg_err "ERROR! CORRUPTED SQUID PROXY"
				sleep 2
				fun_connections
			fi
			cat <<-EOF >$var_pay
				.claro.com.br/
				.claro.com.sv/
				.facebook.net/
				.netclaro.com.br/
				.speedtest.net/
				.tim.com.br/
				.vivo.com.br/
				.oi.com.br/
			EOF
			cat <<-EOF >$var_sqd
				acl url1 dstdomain -i 127.0.0.1
				acl url2 dstdomain -i localhost
				acl url3 dstdomain -i $ipdovps
				acl url4 dstdomain -i /SSHPLUS?
				acl payload url_regex -i "$var_pay"
				acl all src 0.0.0.0/0

				http_access allow url1
				http_access allow url2
				http_access allow url3
				http_access allow url4
				http_access allow payload
				http_access deny all

				#Portas
			EOF
			for Pts in $(echo -e $portass); do
				echo -e "http_port $Pts" >>$var_sqd
				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
			done
			cat <<-EOF >>$var_sqd
				#Nome squid
				visible_hostname vpnunderground.com
				via off
				forwarded_for off
				pipeline_prefetch off
			EOF
			sqd_conf() {
				[[ -d "/etc/squid/" ]] && {
					service ssh restart
					/etc/init.d/squid start
					service squid restart
				}
				[[ -d "/etc/squid3/" ]] && {
					service ssh restart
					/etc/init.d/squid3 start
					service squid3 restart
				}
			}
			echo ""
			color_echo "CONFIGURING SQUID PROXY" "green"
			echo ""
			fun_bar 'sqd_conf'
			echo ""
			msg_ok "SQUID SUCCESSFULLY INSTALLED!"
			sleep 2.5s
			fun_connections
		fi
	}

	addpt_sqd() {
		banner_info "         ADD PORT TO SQUID         "
		echo -e "\n\033[1;33mPORTS IN USE: \033[1;32m$sqdp\n"
		if [[ -f "/etc/squid/squid.conf" ]]; then
			var_sqd="/etc/squid/squid.conf"
		elif [[ -f "/etc/squid3/squid.conf" ]]; then
			var_sqd="/etc/squid3/squid.conf"
		else
			echo -e "\n\033[1;31mSQUID IS NOT INSTALLED!\033[0m"
			echo -e "\n\033[1;31mReturning...\033[0m"
			sleep 2
			clear
			fun_squid
		fi
		echo -ne "\033[1;32mWHICH PORT YOU WANT TO ADD \033[1;33m?\033[1;37m "
		read pt
		[[ -z "$pt" ]] && {
			echo ""
			msg_err "Invalid port!"
			sleep 2
			clear
			fun_connections
		}
		verif_ptrs $pt
		echo ""
		color_echo "ADDING PORT TO SQUID!" "green"
		echo ""
		sed -i "s/#Portas/#Portas\nhttp_port $pt/g" $var_sqd
		fun_bar 'sleep 2'
		echo ""
		color_echo "RESTARTING SQUID!" "green"
		echo ""
		fun_bar 'service squid restart' 'service squid3 restart'
		echo ""
		msg_ok "SUCCESSFULLY ADDED PORT!"
		sleep 3
		clear
		fun_squid
	}

	rempt_sqd() {
		banner_info_red "        REMOVE SQUID PORT        "
		echo -e "\n\033[1;33mPORTS IN USE: \033[1;32m$sqdp\n"
		if [[ -f "/etc/squid/squid.conf" ]]; then
			var_sqd="/etc/squid/squid.conf"
		elif [[ -f "/etc/squid3/squid.conf" ]]; then
			var_sqd="/etc/squid3/squid.conf"
		else
			echo -e "\n\033[1;31mSQUID IS NOT INSTALLED!\033[0m"
			echo -e "\n\033[1;31mReturning...\033[0m"
			sleep 2
			clear
			fun_squid
		fi
		color_echo_n "WHICH PORT YOU WANT TO REMOVE " "green"
		color_echo_n "?" "yellow"
		color_echo_n " " "white"
		read pt
		[[ -z "$pt" ]] && {
			echo ""
			msg_err "Invalid port!"
			sleep 2
			clear
			fun_connections
		}
		if grep -E "$pt" $var_sqd >/dev/null 2>&1; then
			echo ""
			color_echo "REMOVING SQUID PORT!" "green"
			echo ""
			sed -i "/http_port $pt/d" $var_sqd
			fun_bar 'sleep 3'
			echo ""
		color_echo "RESTARTING SQUID!" "green"
			echo ""
			fun_bar 'service squid restart' 'service squid3 restart'
			echo ""
			msg_ok "SUCCESSFULLY REMOVED PORT!"
			sleep 3.5s
			clear
			fun_squid
		else
			echo ""
			color_echo_n "PORT " "red"
			color_echo_n "$pt " "green"
			color_echo "NOT FOUND!" "red"
			sleep 3.5s
			clear
			fun_squid
		fi
	}

	fun_squid() {
		[[ "$(netstat -nplt | grep -c 'squid')" = "0" ]] && inst_sqd
		banner_info "          MANAGE SQUID PROXY           "
		[[ "$(netstat -nplt | grep -c 'squid')" != "0" ]] && {
			sqdp=$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)
			echo -e "\n\033[1;33mPORTS\033[1;37m: \033[1;32m$sqdp"
			VarSqdOn="REMOVE SQUID PROXY"
		} || {
			VarSqdOn="INSTALL SQUID PROXY"
		}
		echo ""
		# Use menu_option function for menu items
		menu_option "1" "$VarSqdOn" "red" "yellow"
		menu_option "2" "ADD PORT" "red" "yellow"
		menu_option "3" "REMOVE PORT" "red" "yellow"
		menu_option "0" "BACK" "red" "yellow"
		echo ""
		color_echo_n "PLEASE SELECT FROM OPTIONS " "green"
		color_echo_n "" "yellow"
		color_echo_n "" "red"
		color_echo_n "" "white"
		read x
		clear
		case $x in
		1 | 01)
			inst_sqd
			;;
		2 | 02)
			addpt_sqd
			;;
		3 | 03)
			rempt_sqd
			;;
		0 | 00)
			echo -e "\033[1;31mReturning...\033[0m"
			sleep 1
			fun_connections
			;;
		*)
			msg_err "Invalid Option..."
			sleep 2
			fun_connections
			;;
		esac
	}

	fun_drop() {
		if netstat -nltp | grep 'dropbear' 1>/dev/null 2>/dev/null; then
			clear
			[[ $(netstat -nltp | grep -c 'dropbear') != '0' ]] && dpbr=$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs) || sqdp="\033[1;31mUNAVAILABLE"
			if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
				stats='\033[1;32m◉ '
			else
				stats='\033[1;31m○ '
			fi
			banner_info "              MANAGE DROPBEAR               "
			echo -e "\n\033[1;33mPORTS\033[1;37m: \033[1;32m$dpbr"
			echo ""
			# Use menu_option function for menu items
			menu_option "1" "LIMIT DROPBEAR $stats" "red" "yellow"
			menu_option "2" "CHANGE DROPBEAR PORT" "red" "yellow"
			menu_option "3" "REMOVE DROPBEAR" "red" "yellow"
			menu_option "0" "BACK" "red" "yellow"
			echo ""
			color_echo_n "PLEASE SELECT FROM OPTIONS " "green"
		color_echo_n "?" "yellow"
		color_echo_n " " "white"
			read resposta
			if [[ "$resposta" = '1' ]]; then
				clear
				if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
					echo -e "\033[1;32mStopping the limiter... \033[0m"
					echo ""
					fun_stplimiter() {
						pidlimiter=$(ps x | grep "limiter" | awk -F "pts" {'print $1'})
						kill -9 $pidlimiter
						screen -wipe
					}
					fun_bar 'fun_stplimiter' 'sleep 2'
					echo -e "\n\033[1;31m LIMITER OFF \033[0m"
					sleep 3
					fun_drop
				else
					echo -e "\n\033[1;32mStarting the limiter... \033[0m"
					echo ""
					fun_bar 'screen -d -m -t limiter droplimiter' 'sleep 3'
					echo -e "\n\033[1;32m  LIMITER ON \033[0m"
					sleep 3
					fun_drop
				fi
			elif [[ "$resposta" = '2' ]]; then
				echo ""
				color_echo_n "WHICH PORT DO YOU WANT TO USE " "green"
				color_echo_n "?" "yellow"
				color_echo_n " " "white"
				read pt
				echo ""
				verif_ptrs $pt
				var1=$(grep 'DROPBEAR_PORT=' /etc/default/dropbear | cut -d'=' -f2)
				echo -e "\033[1;32mCHANGING PORT DROPBEAR!"
				sed -i "s/\b$var1\b/$pt/g" /etc/default/dropbear >/dev/null 2>&1
				echo ""
				fun_bar 'sleep 2'
				echo -e "\n\033[1;32mRESETTING DROPBEAR!"
				echo ""
				fun_bar 'service dropbear restart' '/etc/init.d/dropbear restart'
				echo ""
				msg_ok "PORT CHANGED SUCCESSFULLY!"
				sleep 3
				clear
				fun_connections
			elif [[ "$resposta" = '3' ]]; then
				echo ""
				color_echo "REMOVING DROPBEAR !" "green"
				echo ""
				fun_dropunistall() {
					service dropbear stop && /etc/init.d/dropbear stop
					apt-get autoremove dropbear -y
					apt-get remove dropbear-run -y
					apt-get remove dropbear -y
					apt-get purge dropbear -y
					rm -rf /etc/default/dropbear
				}
				fun_bar 'fun_dropunistall'
				echo ""
				msg_ok "SUCCESSFULLY REMOVED DROPBEAR !"
				sleep 3
				clear
				fun_connections
			elif [[ "$resposta" = '0' ]]; then
				echo ""
				msg_err "Returning..."
				sleep 2
				fun_connections
			else
				echo ""
				msg_err "Invalid option..."
				sleep 2
				fun_connections
			fi
		else
			clear
			banner_info "           DROPBEAR INSTALLER              "
			echo -e "\n\033[1;33mYOU ARE ABOUT TO INSTALL DROPBEAR !\033[0m\n"
			color_echo_n "DO YOU WANT TO CONTINUE " "green"
			color_echo_n "? " "red"
			color_echo_n "[y/n]: " "yellow"
			read resposta
			[[ "$resposta" = 'y' ]] && {
				echo -e "\n\033[1;33mDEFINE A PORT FOR DROPBEAR !\033[0m\n"
				echo -ne "\033[1;32mSELECT A PORT \033[1;33m?\033[1;37m "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
				msg_err "Invalid port!"
					sleep 3
					clear
					fun_connections
				}
				verif_ptrs $porta
				echo ""
				color_echo "INSTALLING DROPBEAR !" "green"
				echo ""
				fun_instdrop() {
					apt-get update -y
					apt-get install dropbear -y
				}
				fun_bar 'fun_instdrop'
				fun_ports() {
					sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear >/dev/null 2>&1
					sed -i "s/DROPBEAR_PORT=22/DROPBEAR_PORT=$porta/g" /etc/default/dropbear >/dev/null 2>&1
					sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 110"/g' /etc/default/dropbear >/dev/null 2>&1
				}
				echo ""
				color_echo "CONFIGURING DROPBEAR PORT !" "green"
				echo ""
				fun_bar 'fun_ports'
				grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
				echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
				grep -v "^PermitTunnel yes" /etc/ssh/sshd_config >/tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
				echo "PermitTunnel yes" >>/etc/ssh/sshd_config
				echo ""
				echo -e "\033[1;32mFINISHING INSTALLATION !\033[0m"
				echo ""
				fun_ondrop() {
					service dropbear start
					/etc/init.d/dropbear restart
				}
				fun_bar 'fun_ondrop' 'sleep 1'
				echo -e "\n\033[1;32mINSTALLATION COMPLETED \033[1;33mPORT: \033[1;37m$porta\033[0m"
				[[ $(grep -c "/bin/false" /etc/shells) = '0' ]] && echo "/bin/false" >>/etc/shells
				sleep 2
				clear
				fun_connections
			} || {
				echo""
				echo -e "\033[1;31mReturning...\033[0m"
				sleep 3
				clear
				fun_connections
			}
		fi
	}

	fun_socks() {
		clear
		banner_info "            MANAGING SOCKS PROXY            "
		echo ""
		[[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
			sks='\033[1;32mON'
			color_echo_n "PORTS: " "yellow"
			color_echo "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" "green"
		} || {
			red_code=$(get_color_code "red")
			sks="${red_code}OFF"
		}
		green_code=$(get_color_code "green")
		red_code=$(get_color_code "red")
		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="${green_code}◉" || var_sks1="${red_code}○"
		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="${green_code}◉" || sksop="${red_code}○"
		echo ""
		# Use menu_option function for menu items
		menu_option "1" "SOCKS SSH $var_sks1" "red" "yellow"
		menu_option "2" "SOCKS OPENVPN $sksop" "red" "yellow"
		menu_option "3" "OPEN PORT" "red" "yellow"
		menu_option "4" "CHANGE STATUS" "red" "yellow"
		menu_option "0" "BACK" "red" "yellow"
		echo ""
		color_echo_n "PLEASE SELECT FROM OPTIONS " "green"
		color_echo_n "?" "yellow"
		color_echo_n " " "white"
		read resposta
		if [[ "$resposta" = '1' ]]; then
			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				banner_info_red "             PROXY SOCKS              "
				echo ""
				fun_socksoff() {
					for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					[[ $(grep -wc "proxy.py" /etc/autostart) != '0' ]] && {
						sed -i '/proxy.py/d' /etc/autostart
					}
					sleep 1
					screen -wipe >/dev/null
				}
				color_echo "DISABLING SOCKS PROXY" "green"
				echo ""
				fun_bar 'fun_socksoff'
				echo ""
				msg_ok "SOCKS PROXY DISABLED SUCCESSFULLY!"
				sleep 3
				fun_socks
			else
				clear
				banner_info "             SOCKS PROXY              "
				echo ""
				echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					msg_err "Invalid port!"
					sleep 3
					clear
					fun_connections
				}
				verif_ptrs $porta
				fun_inisocks() {
					sleep 1
					screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
					[[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy python /etc/SSHPlus/proxy.py $porta" >>/etc/autostart
					} || {
						sed -i '/proxy.py/d' /etc/autostart
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy python /etc/SSHPlus/proxy.py $porta" >>/etc/autostart
					}
				}
				echo ""
				echo -e "\033[1;32mSTARTING SOCKS PROXY\033[1;33m"
				echo ""
				fun_bar 'fun_inisocks'
				echo ""
				msg_ok "SOCKS ENABLED SUCCESSFULLY"
				sleep 3
				fun_socks
			fi
		elif [[ "$resposta" = '2' ]]; then
			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				banner_info_red "            SOCKS OPENVPN             "
				echo ""
				fun_socksopenoff() {
					for pidproxy in $(screen -list | grep -w "openpy" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					[[ $(grep -wc "open.py" /etc/autostart) != '0' ]] && {
						sed -i '/open.py/d' /etc/autostart
					}
					sleep 1
					screen -wipe >/dev/null
				}
				color_echo "DEACTIVATING THE SOCKS OPENVPN" "green"
				echo ""
				fun_bar 'fun_socksopenoff'
				echo ""
				echo -e "\033[1;32mSOCKS OFF WITH SUCCESS!\033[1;33m"
				sleep 2
				fun_socks
			else
				clear
				banner_info_red "            SOCKS OPENVPN             "
				echo ""
				echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					msg_err "Invalid port!"
					sleep 2
					clear
					fun_connections
				}
				verif_ptrs $porta
				fun_inisocksop() {
					[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
						listoldop=$(grep -w 'DEFAULT_HOST =' /etc/SSHPlus/open.py | cut -d"'" -f2 | cut -d: -f2)
						listopen=$(netstat -tlpn | grep -w openvpn | grep -v 127.0.0.1 | awk {'print $4'} | cut -d: -f2)
						sed -i "s/$listoldop/$listopen/" /etc/SSHPlus/open.py
					}
					sleep 1
					screen -dmS openpy python /etc/SSHPlus/open.py $porta
					[[ $(grep -wc "open.py" /etc/autostart) = '0' ]] && {
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS openpy python /etc/SSHPlus/open.py $porta" >>/etc/autostart
					} || {
						sed -i '/open.py/d' /etc/autostart
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS openpy python /etc/SSHPlus/open.py $porta" >>/etc/autostart
					}
				}
				echo ""
				echo -e "\033[1;32mSTARTING SOCKS OPENVPN\033[1;33m"
				echo ""
				fun_bar 'fun_inisocksop'
				echo ""
				echo -e "\033[1;32mSOCKS OPENVPN ACTIVATED WITH SUCCESS\033[1;33m"
				sleep 3
				fun_socks
			fi
		elif [[ "$resposta" = '3' ]]; then
			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
				clear
				echo -e "\E[44;1;37m            SOCKS PROXY            \E[0m"
				echo ""
				echo -e "\033[1;33mPORTS IN USE: \033[1;32m$sockspt"
				echo ""
				echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					msg_err "Invalid port!"
					sleep 2
					clear
					fun_connections
				}
				verif_ptrs $porta
				echo ""
				echo -e "\033[1;32mSTARTING SOCKS PROXY IN PORT \033[1;31m$porta\033[1;33m"
				echo ""
				abrirptsks() {
					sleep 1
					screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
					sleep 1
				}
				fun_bar 'abrirptsks'
				echo ""
				echo -e "\033[1;32mSOCKS PROXY ACTIVATED SUCCESSFULLY\033[1;33m"
				sleep 2
				fun_socks
			else
				clear
				echo -e "\033[1;31mFUNCTION UNAVAILABLE\n\n\033[1;33mACTIVATE SOCKS FIRST !\033[1;33m"
				sleep 2
				fun_socks
			fi
		elif [[ "$resposta" = '4' ]]; then
			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
				echo -e "\E[44;1;37m             SOCKS PROXY             \E[0m"
				echo ""
				color_echo_n "STATUS: " "yellow"
				color_echo "$msgsocks" "green"
				echo""
				echo -ne "\033[1;32mINFORM YOUR STATUS\033[1;31m:\033[1;37m "
				read msgg
				[[ -z "$msgg" ]] && {
					echo ""
					msg_err "Invalid status!"
					sleep 2
					fun_connections
				}
				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
					# Use color function for error message - handles fallback internally
					echo ""
					msg_warn "[!] AVOID SPECIAL CHARACTERS"
					sleep 2
					fun_socks
				}
				# Use the color menu function - handles fallback internally
				show_color_menu
				# Use color function for prompt - handles fallback internally
				color_echo_n "SELECT A COLOR" "green"
				color_echo_n " ?" "red"
				color_echo_n " : " "white"
				read sts_cor
				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
					cor_sts='blue'
				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
					cor_sts='green'
				elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
					cor_sts='red'
				elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
					cor_sts='yellow'
				elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
					cor_sts='#F535AA'
				elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
					cor_sts='cyan'
				elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
					cor_sts='#FF7F00'
				elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
					cor_sts='#9932CD'
				elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
					cor_sts='black'
				elif [[ "$sts_cor" = "10" ]]; then
					cor_sts='null'
				else
					echo -e "\n\033[1;33mINVALID OPTION !"
					cor_sts='null'
				fi
				fun_msgsocks() {
					msgsocks2=$(cat /etc/SSHPlus/proxy.py | grep "MSG =" | awk -F = '{print $2}')
					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/SSHPlus/proxy.py
					sleep 1
					cor_old=$(grep 'color=' /etc/SSHPlus/proxy.py | cut -d '"' -f2)
					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/proxy.py

				}
				echo ""
				color_echo "CHANGING STATUS!" "green"
				echo ""
				fun_bar 'fun_msgsocks'
				restartsocks() {
					if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_sks
						for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
							screen -r -S "$pidproxy" -X quit
						done
						screen -wipe >/dev/null
						_Ptsks="$(cat /tmp/Pt_sks)"
						sleep 1
						screen -dmS proxy python /etc/SSHPlus/proxy.py $_Ptsks
						rm /tmp/Pt_sks
					fi
				}
				echo ""
				color_echo "RESTARTING PROXY SOCKS!" "green"
				echo ""
				fun_bar 'restartsocks'
				echo ""
				msg_ok "STATUS CHANGED SUCCESSFULLY!"
				sleep 2
				fun_socks
			else
				clear
				echo -e "\033[1;31mFUNCTION UNAVAILABLE\n\n\033[1;33mACTIVATE SOCKS SSH FIRST !\033[1;33m"
				sleep 2
				fun_socks
			fi
		elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mReturning...\033[0m"
			sleep 1
			fun_connections
		else
			echo ""
			msg_err "Invalid option !"
			sleep 1
			fun_socks
		fi

	}

	fun_openssh() {
		# Directly call the multi-port setup module
		if [[ -f "/bin/multiport" ]]; then
			/bin/multiport
		elif [[ -f "/etc/SSHPlus/multiport" ]]; then
			/etc/SSHPlus/multiport
		elif [[ -f "$(dirname "$0")/multiport" ]]; then
			"$(dirname "$0")/multiport"
		else
			clear
			msg_err "Multi-port module not found!"
			sleep 2
		fi
		fun_connections
	}

	x="ok"
	fun_connections() {
		while true $x != "ok"; do
			[[ ! -e '/home/sshplus' ]] && exit 0
			clear
			banner_info "                CONNECTION MODE                 "
			echo ""
			echo -e "\033[1;32mSERVICE: \033[1;33mOPENSSH \033[1;32mPORT: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "

			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mSSLH: \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts7="\033[1;32m◉ "
			} || {
				sts7="\033[1;31m○ "
			}

			[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mOPENVPN: \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts5="\033[1;32m◉ "
			} || {
				sts5="\033[1;31m○ "
			}

			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mSOCKS PROXY \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts4="\033[1;32m◉ "
			} || {
				sts4="\033[1;31m○ "
			}
			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mSSL TUNNEL \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts3="\033[1;32m◉ "
			} || {
				sts3="\033[1;31m○ "
			}
			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mDROPBEAR \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
				sts2="\033[1;32m◉ "
			} || {
				sts2="\033[1;31m○ "
			}
			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mSQUID PROXY\033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
				sts1="\033[1;32m◉ "
			} || {
				sts1="\033[1;31m○ "
			}
			# Use color codes for menu borders and items
			blue_code=$(get_color_code "blue")
			red_code=$(get_color_code "red")
			cyan_code=$(get_color_code "cyan")
			white_code=$(get_color_code "white")
			yellow_code=$(get_color_code "yellow")
			green_code=$(get_color_code "green")
			reset_code=$(get_reset_code)
			echo -e "${blue_code}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${reset_code}"
			echo ""
			# Use color codes for main connection menu
			echo -e "${red_code}[${cyan_code}01${red_code}] ${white_code}• ${yellow_code}OPENSSH $sts6${reset_code}"
			echo -e "${red_code}[${cyan_code}02${red_code}] ${white_code}• ${yellow_code}SQUID PROXY $sts1${reset_code}"
			echo -e "${red_code}[${cyan_code}03${red_code}] ${white_code}• ${yellow_code}DROPBEAR $sts2${reset_code}"
			echo -e "${red_code}[${cyan_code}04${red_code}] ${white_code}• ${yellow_code}Install_SO $sts5${reset_code}"
			echo -e "${red_code}[${cyan_code}05${red_code}] ${white_code}• ${yellow_code}SOCKS PROXY $sts4${reset_code}"
			echo -e "${red_code}[${cyan_code}06${red_code}] ${white_code}• ${yellow_code}SSL+PY Websocket $sts3${reset_code}"
			echo -e "${red_code}[${cyan_code}07${red_code}] ${white_code}• ${yellow_code}WS_EPRO $sts7${reset_code}"
			echo -e "${red_code}[${cyan_code} 0${red_code}] ${white_code}• ${yellow_code}BACK ${green_code}<${yellow_code}<${red_code}<${reset_code}"
			echo -e "${red_code}[${cyan_code}00${red_code}] ${white_code}• ${yellow_code}SALIR❌ ${green_code}<${yellow_code}<${red_code}<${reset_code}"
			echo ""
			echo -e "${blue_code}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${reset_code}"
			echo ""
			tput civis
			color_echo_n " ELEGIR UNA OPCION " "green"
			color_echo_n "?" "yellow"
			color_echo_n "?" "red"
			color_echo_n " " "white"
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
				fun_openssh
				;;
			2 | 02)
				fun_squid
				;;
			3 | 03)
				fun_drop
				;;
			4 | 04)
				bash <(wget -qO- https://raw.githubusercontent.com/nandoslayer/vps-reinstaller/main/install.sh)
				;;
			5 | 05)
				fun_socks
				;;
			6 | 06)
				rm -rf /root/*   && wget https://gitlab.com/diegovip7/SSHPLUS/-/raw/main/Modulos/ubuntu22.sh && chmod +x ubuntu22.sh && ./ubuntu22.sh
		sleep 5
		fun_connections
				;;
			7 | 07)
				wget 'https://gitlab.com/diegovip7/2d/-/raw/main/install-ws.bin' -O 'install-ws' && chmod +x install-ws && ./install-ws
				;;
			0)
				menu
				;;
			00)
				echo -e "\033[1;31mC H A U U U 🖐🏻🇦🇷🇦🇷...\033[0m"
				sleep 2
				clear
				exit
				;;
			*)
				msg_err "Opcion Error !"
				sleep 2
				;;
			esac
		done
	}
	fun_connections
}
